### ISSUE TITLE
Create a more informative error message when the return string is larger than 4GiB

### ISSUE THREAD

**Issue by crosenth** [crosenth/medirect#3]
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/usr/local/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
OverflowError: cannot serialize a string larger than 4GiB

**Comment by crosenth** [comment]
Stale
